server:
  port: 9008

spring:
  application:
    name: learning_service

  datasource:
    url: jdbc:mysql://localhost:3306/learning_service
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false

storage:
  provider: local
  local-root: ./storage
  public-base-url:
  max-file-size-bytes: 10485760
  minio-endpoint: http://localhost:9000
  minio-access-key: minioadmin
  minio-secret-key: minioadmin
  minio-bucket: learning-service
  presigned-url-expiry-seconds: 900
